spring.application.name=petistan-gateway-server
server.port=8080

# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}.${spring.application.instance_id:${random.value}}

# Gateway Configuration
spring.cloud.gateway.server.webflux.routes[0].id=petistan-owner-microservice
spring.cloud.gateway.server.webflux.routes[0].uri=lb://petistan-owner-microservice
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/petistan/owner/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[1].id=petistan-pet-microservice
spring.cloud.gateway.server.webflux.routes[1].uri=lb://petistan-pet-microservice
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/petistan/pet/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[2].id=petistan-mail-microservice
spring.cloud.gateway.server.webflux.routes[2].uri=lb://petistan-mail-microservice
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/petistan/mail/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1
