spring.application.name=petistan-owner-microservice

#
# pet.service.base.url=http://localhost:8082/pet
# This can be replaced by 
# pet.service.base.url=http://petistan-pet-MS/pet
# It is case in-sensitive 
#

pet.service.base.url=http://petistan-pet-microservice/pet
mail.service.base.url=http://petistan-mail-microservice/mail/send

# These 2 not required because it is handled automatically by Eureka Server
#spring.cloud.discovery.client.simple.instances.petistan-mail-MS[0].uri=http://localhost:8083
#spring.cloud.discovery.client.simple.instances.petistan-mail-MS[1].uri=http://localhost:8084

spring.config.import=configserver:http://localhost:8888

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

eureka.instance.instance-id=${spring.application.name}.${spring.application.instance_id:${random.value}}

resilience4j.retry.instances.petRetry.max-attempts=3
resilience4j.retry.instances.petRetry.wait-duration=1s
resilience4j.retry.instances.petRetry.enable-exponential-backoff=true
# this will make calls wait time exponential by 2
resilience4j.retry.instances.petRetry.exponentialBackoffMultiplier=2

resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.sliding-window-size=10
resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.automatic-transition-from-open-to-half-open-enabled=true
