spring.application.name=Petistan-Discovery-Server

#Default Port Number
server.port=8761

#By this Eureka server will not Register itself as client
eureka.client.register-with-eureka=false
#By this eureka server will not wait for other server fetching
eureka.client.fetch-registry=false