spring.application.name=petistan-pet-microservice

# Consul Configuration
spring.config.import=consul:
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.config.format=properties

spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}.${spring.application.instance_id:${random.value}}

# Distributed Tracing - Zipkin
management.tracing.sampling.probability=1.0