spring.application.name=petistan-owner-microservice

pet.service.base.url=http://petistan-pet-microservice/pet

spring.config.import=configserver:http://localhost:8888

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

eureka.instance.instance-id=${spring.application.name}.${spring.application.instance_id:${random.value}}

resilience4j.retry.instances.petRetry.max-attempts=3
resilience4j.retry.instances.petRetry.wait-duration=1s
resilience4j.retry.instances.petRetry.enable-exponential-backoff=true
# this will make calls wait time exponential by 2
resilience4j.retry.instances.petRetry.exponentialBackoffMultiplier=2

resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.sliding-window-size=10
resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.circuitBreakerForFindPet.automatic-transition-from-open-to-half-open-enabled=true


management.tracing.sampling.probability=1.0
